general:
    log: {level: info, filename: null, filemode: null, format: null, datefmt: null}
    outdir: .
    n_jobs: 1
    datasets_file: null
    models_file: null
observations:
    datastore: /home/antonio/Analysis/GAMMAPY/GammaCygni
    obs_ids: []
    obs_file: null
    obs_cone: {frame: galactic, lon: null, lat: 2.0 deg, radius: 5.0 deg}
    obs_time: {start: null, stop: null}
    required_irf: [aeff, edisp, psf, bkg]
datasets:
    type: 3d
    stack: true
    geom:
        wcs:
            skydir: {frame: null, lon: null, lat: null}
            binsize: 0.1 deg
            width: {width: 10.0 deg, height: 8.0 deg}
            binsize_irf: 0.2 deg
        selection: {offset_max: 2.5 deg}
        axes:
            energy: {min: 0.7 TeV, max: 100.0 TeV, nbins: 20}
            energy_true: {min: 0.1 TeV, max: 200.0 TeV, nbins: 30}
    map_selection: [counts, exposure, background, psf, edisp]
    background:
        method: fov_background
        exclusion: null
        parameters: {method: scale}
    safe_mask:
        methods: [aeff-default]
        parameters: {}
    on_region: {frame: null, lon: null, lat: null, radius: null}
    containment_correction: true
fit:
    fit_range: {min: 0.7 TeV, max: 100.0 TeV}
flux_points:
    energy: {min: 0.7 TeV, max: 100.0 TeV, nbins: 20}
    source: source
    parameters: {selection_optional: all}
excess_map:
    correlation_radius: 0.1 deg
    parameters: {}
    energy_edges: {min: null, max: null, nbins: null}
light_curve:
    time_intervals: {start: null, stop: null}
    energy_edges: {min: null, max: null, nbins: null}
    source: source
    parameters: {selection_optional: all}
